[toolchain]
channel = "nightly-2025-11-01"
components = [
  "cargo",
  "clippy",
  "rustc",
  "rustfmt",
  "rust-analyzer",
  "rust-docs",
  "rust-src",
  "rust-std",
  "miri",          # for unsafe code testing
]
